"""Remove subject from grade

Revision ID: 451981e8faa3
Revises: a19a62e9247e
Create Date: 2025-09-14 22:35:18.155572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '451981e8faa3'
down_revision: Union[str, Sequence[str], None] = 'a19a62e9247e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grades_subject'), table_name='grades')
    op.drop_column('grades', 'subject')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grades', sa.Column('subject', sa.VARCHAR(), nullable=True))
    op.create_index(op.f('ix_grades_subject'), 'grades', ['subject'], unique=False)
    # ### end Alembic commands ###
