"""add drawing history

Revision ID: 9052ae5fa33a
Revises: cd817de4ec37
Create Date: 2025-09-22 18:36:50.652823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9052ae5fa33a'
down_revision: Union[str, Sequence[str], None] = 'cd817de4ec37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('drawing_history',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('classroom_id', sa.Integer(), nullable=True),
    # sa.Column('drawing_date', sa.DateTime(), nullable=True),
    # sa.Column('drawn_students', sa.JSON(), nullable=True),
    # sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # with op.batch_alter_table('drawing_history', schema=None) as batch_op:
    #     batch_op.create_index(batch_op.f('ix_drawing_history_id'), ['id'], unique=False)
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drawing_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drawing_history_id'))

    op.drop_table('drawing_history')
    # ### end Alembic commands ###
