"""add groups table

Revision ID: a80d75d0955a
Revises: 6841d3de6446
Create Date: 2025-10-07 15:08:54.214817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a80d75d0955a'
down_revision: Union[str, Sequence[str], None] = '6841d3de6446'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('classroom_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_groups_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_groups_name'), ['name'], unique=False)

    op.create_table('student_group_association',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id', 'group_id')
    )
    op.drop_table('student_subgroup_association')
    with op.batch_alter_table('subgroups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subgroups_id'))
        batch_op.drop_index(batch_op.f('ix_subgroups_name'))

    op.drop_table('subgroups')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subgroups',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('classroom_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subgroups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subgroups_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_subgroups_id'), ['id'], unique=False)

    op.create_table('student_subgroup_association',
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.Column('subgroup_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subgroup_id'], ['subgroups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id', 'subgroup_id')
    )
    op.drop_table('student_group_association')
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_groups_name'))
        batch_op.drop_index(batch_op.f('ix_groups_id'))

    op.drop_table('groups')
    # ### end Alembic commands ###
