"""Add cascade delete to students

Revision ID: de96a1a8bbe2
Revises: f4561f8a0c87
Create Date: 2025-09-19 13:23:27.316995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de96a1a8bbe2'
down_revision: Union[str, Sequence[str], None] = 'f4561f8a0c87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_students_classroom_id', 'classrooms', ['classroom_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint('fk_students_classroom_id', type_='foreignkey')

    # ### end Alembic commands ###
