"""Add cascade delete to grades

Revision ID: f4561f8a0c87
Revises: 419400ab9359
Create Date: 2025-09-19 13:12:56.877126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4561f8a0c87'
down_revision: Union[str, Sequence[str], None] = '419400ab9359'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_grades_student_id', 'students', ['student_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.drop_constraint('fk_grades_student_id', type_='foreignkey')

    # ### end Alembic commands ###
